//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem_Helsinki.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Der
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Der()
        {
            this.Oda_Dersleri = new HashSet<Oda_Dersleri>();
            this.Sinavlars = new HashSet<Sinavlar>();
        }
    
        public int id { get; set; }
        public string ders_adi { get; set; }
        public string ders_referans { get; set; }
        public int kredi { get; set; }
        public Nullable<int> ref_bolum { get; set; }
        public Nullable<int> active { get; set; }
    
        public virtual Bolum Bolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oda_Dersleri> Oda_Dersleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sinavlar> Sinavlars { get; set; }
    }
}
