//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem_Helsinki.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.Kullanicis = new HashSet<Kullanici>();
            this.Oda_Personel = new HashSet<Oda_Personel>();
            this.Sinavlars = new HashSet<Sinavlar>();
        }
    
        public int id { get; set; }
        public string adi { get; set; }
        public string soyad { get; set; }
        public string yas { get; set; }
        public Nullable<System.DateTime> mezun_tarih { get; set; }
        public Nullable<int> sinif { get; set; }
        public int ref_bolum { get; set; }
        public int ref_okul { get; set; }
        public Nullable<int> active { get; set; }
    
        public virtual Bolum Bolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanici> Kullanicis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oda_Personel> Oda_Personel { get; set; }
        public virtual Okul Okul { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sinavlar> Sinavlars { get; set; }
    }
}
